Exception: drop constraint in parsed_file
This parameter can either Str or a Path::Tiny object. Since this
parameter is concatenated, let's assume it's a string or an object
that can be stringified.